# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            node-version: [10.x]

      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: ${{ matrix.node-version }}
         - run: npm ci
         - run: npm run build --if-present
         - run: npm run test
           env:
              MONGO_URI: ${{ secrets.MONGO_URI }}
              JWT_SECRET: ${{ secrets.JWT_SECRET }}
              MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
              JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
              JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
              IMDB_KEY: ${{ secrets.IMDB_KEY }}
              PORT: ${{ secrets.PORT }}
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v1
         - name: Setup Docker Buildx
           uses: docker/setup-buildx-action@v1
         - name: Login Docker
           if: success()
           uses: docker/login-action@v1
           with:
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}
         - name: Build and push
           id: docker_build
           uses: docker/build-push-action@v2
           with:
             context: .
             push: true
             tags: movie-api/app:latest
