# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            node-version: [10.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: ${{ matrix.node-version }}
         - run: npm ci
         - run: npm run build --if-present
         - run: npm run test
           env:
              MONGO_URI: mongodb+srv://bart123:bart123@cluster0.hcu1x.mongodb.net/movies-api?retryWrites=true&w=majority
              JWT_SECRET: secret
              MONGO_URI_TEST: mongodb+srv://bart123:bart123@cluster0.hcu1x.mongodb.net/movies-api-test?retryWrites=true&w=majority
              JWT_EXPIRE: 30m
              JWT_ISSUER: https://www.netguru.com/
              IMDB_KEY: 262b69da
              PORT: 3000
          - name: Publish Docker
              if: success()
              uses: elgohr/Publish-Docker-Github-Action@2.11
              with:
                name: movie-api/nodejs_githubactions
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_PASS }}